/**
 * Populate DB with sample data on server start
 * to disable, edit config/environment/index.js, and set `seedDB: false`
 */

'use strict';

var User = require('../api/user/user.model');
var Player = require('../api/player/player.model');

Player.find({}).remove(function() {
  Player.create({
    email:      'cr7@mail.com',
    nombre:     'Cristiano',
    apellidos:  'Ronaldo',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Madrid',
    foto:       'http://imalbum.aufeminin.com/album/D20140505/cristiano-ronaldo-1-1051426_H221342_L.jpg',
    posicion:   'Delantero',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'Elena@mail.com',
    nombre:     'Elena',
    apellidos:  'Carrasco',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Almería',
    foto:       'https://media.licdn.com/media/p/1/000/108/053/3f15e2b.jpg',
    posicion:   'No tiene',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'alves@mail.com',
    nombre:     'Dani',
    apellidos:  'Alves',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Barcelona',
    foto:       'http://arxiu.fcbarcelona.cat/web/thumbnails/199_150/Imatges/2010-2011/Futbol/primer_equip/plantilla/ALVES.jpg',
    posicion:   'Lateral',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'degea@mail.com',
    nombre:     'David',
    apellidos:  'De Gea',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Madrid',
    foto:       'http://www3.pictures.zimbio.com/gi/David+de+Gea+Manchester+United+FC+v+SL+Benfica+cRx9ZRrIaszl.jpg',
    posicion:   'Portero',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'bale@mail.com',
    nombre:     'Gareth',
    apellidos:  'Bale',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Madrid',
    foto:       'http://highschool.com.do/wp-content/uploads/2013/09/gareth-bale2-600x885.jpg',
    posicion:   'Extremo',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'casillas@mail.com',
    nombre:     'Iker',
    apellidos:  'Casillas',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Madrid',
    foto:       'http://www.realmadrid.com.ro/wp-content/uploads/2014/09/Iker-Casillas.jpg',
    posicion:   'Portero',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'iniesta@mail.com',
    nombre:     'Iniesta',
    apellidos:  '',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Barcelona',
    foto:       'http://arxiu.fcbarcelona.cat/web/thumbnails/199_150/Imatges/2010-2011/Futbol/primer_equip/plantilla/INIESTA.jpg',
    posicion:   'Medio Centro',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'isco@mail.com',
    nombre:     'Isco',
    apellidos:  '',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Madrid',
    foto:       'http://d3.yimg.com/sr/img/1/e003fbb8-86c4-3ff1-917e-f87c04521783',
    posicion:   'Medio Centro',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'james@mail.com',
    nombre:     'James',
    apellidos:  'Rodriguez',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Madrid',
    foto:       'http://www.la-razon.com/marcas/James-Rodriguez-Casa-Blanca-Internet_LRZIMA20140722_0031_11.jpg',
    posicion:   'Medio Centro',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'messi@mail.com',
    nombre:     'Leo',
    apellidos:  'Messi',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Barcelona',
    foto:       'http://www.pasionlibertadores.com/__export/1433373789506/sites/pasionlibertadores/img/2015/06/03/lucas2228794_20150603_0823_lionel-messi_416x416.jpg',
    posicion:   'Medio Centro',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'miguel@mail.com',
    nombre:     'Miguel Angel',
    apellidos:  'Del Aguila',
    edad:       30,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Almería',
    foto:       'https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xpa1/v/t1.0-1/p160x160/1911873_10203355484317603_1705876476_n.jpg?oh=779a4cd6e2ef11bf02c2cd27d6e6924e&oe=55E93607&__gda__=1446176709_1ecab1c596560617df9b948f8809023e',
    posicion:   'Medio Centro',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'neymar@mail.com',
    nombre:     'Neymar',
    apellidos:  '',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Barcelona',
    foto:       'http://datos.elconfidencial.com/test-champions-league-post/img/futbolistas/2/8.jpg',
    posicion:   'Extremo',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'pedro@mail.com',
    nombre:     'Pedro',
    apellidos:  '',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Barcelona',
    foto:       'http://arxiu.fcbarcelona.cat/web/thumbnails/199_150/Imatges/2010-2011/Futbol/primer_equip/plantilla/PEDRO.jpg',
    posicion:   'Extremo',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'raul@mail.com',
    nombre:     'Raul',
    apellidos:  'Gonzalez',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Madrid',
    foto:       'http://www.weloba.es/sites/default/files/images/general/o_real_madrid_raul_gonzalez-860257.jpg',
    posicion:   'Delantero',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'ramos@mail.com',
    nombre:     'Sergio',
    apellidos:  'Ramos',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Madrid',
    foto:       'http://www.corazonblanco.com/media/reportero/44/1/2/4/0/o_20150426151306_las_mil_funciones_de_sergio_ramos.jpg',
    posicion:   'Defensa',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'kross@mail.com',
    nombre:     'Tony',
    apellidos:  'Kross',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Madrid',
    foto:       'http://www.notiminuto.com/site/assets/files/15506/kross.jpg',
    posicion:   'Medio Centro',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'xavi@mail.com',
    nombre:     'Xavi',
    apellidos:  '',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Barcelona',
    foto:       'http://www.weloba.es/sites/default/files/images/general/hi-res-187611879-xavi-hernandez-of-fc-barcelona-looks-on-prior-to-the-la_crop_exact.jpg',
    posicion:   'Medio Centro',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'zidane@mail.com',
    nombre:     'Zidane',
    apellidos:  '',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Madrid',
    foto:       'http://www.realmadrid.com/cs/Satellite?blobcol=urldata&blobheader=image%2Fjpeg&blobkey=id&blobtable=MungoBlobs&blobwhere=1203339998028&ssbinary=true',
    posicion:   'Medio Centro',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  },{
    email:      'ibra@mail.com',
    nombre:     'Zlatan',
    apellidos:  'Ibrahimovic',
    edad:       25,
    altura:     180,
    pie:        'Diestro',
    ciudad:     'Madrid',
    foto:       'http://looktv.ro/wp-content/uploads/2015/02/ibra1.jpg',
    posicion:   'Delantero',
    organizados:0,
    jugados:    0,
    convocado:  0,
    fiabilidad: 0,
    victorias:  0,
    promediovictorias: 0,
    goles:      0,
    promediogoles:0,
    encajados:    0,
    promedioencajados:0,
    solicitudes: [],
    peticiones: [],
    amigos:     []
  });
});

User.find({}).remove(function() {
  User.create({ 
    name: 'Cristiano',
    email: 'cr7@mail.com',
    password: '123'
  },{ 
    name: 'Alves',
    email: 'alves@mail.com',
    password: '123'
  },{ 
    name: 'David',
    email: 'degea@mail.com',
    password: '123'
  },{ 
    name: 'Elena',
    email: 'elena@mail.com',
    password: '123'
  },{ 
    name: 'Gareth',
    email: 'bale@mail.com',
    password: '123'
  },{ 
    name: 'Iker',
    email: 'casillas@mail.com',
    password: '123'
  },{ 
    name: 'Iniesta',
    email: 'iniesta@mail.com',
    password: '123'
  },{ 
    name: 'Isco',
    email: 'isco@mail.com',
    password: '123'
  },{ 
    name: 'James',
    email: 'james@mail.com',
    password: '123'
  },{ 
    name: 'Leo',
    email: 'messi@mail.com',
    password: '123'
  },{ 
    name: 'Miguel Angel',
    email: 'miguel@mail.com',
    password: '123'
  },{ 
    name: 'Neymar',
    email: 'neymar@mail.com',
    password: '123'
  },{ 
    name: 'Pedro',
    email: 'pedro@mail.com',
    password: '123'
  },{ 
    name: 'Raul',
    email: 'raul@mail.com',
    password: '123'
  },{ 
    name: 'Sergio',
    email: 'ramos@mail.com',
    password: '123'
  },{ 
    name: 'Tony',
    email: 'kross@mail.com',
    password: '123'
  },{ 
    name: 'Xavi',
    email: 'xavi@mail.com',
    password: '123'
  },{ 
    name: 'Zidane',
    email: 'zidane@mail.com',
    password: '123'
  },{ 
    name: 'Zlatan',
    email: 'ibra@mail.com',
    password: '123'
  });
    console.log('Finished populating users');
});


